export const en = {
  "meta.title": "What's for dinner?",
  "meta.description":
    "Turn fridge ingredients into an AI cooking prompt, and keep a shopping list of only what you don't have.",
  "app.title": "What's for dinner?",
  "app.lede": "Add ingredients, copy a prompt, paste it into ChatGPT or Claude.",
  "tabs.aria": "Pages",
  "tabs.cook": "Cook",
  "tabs.shop": "Shop",
  "tabs.journal": "Cooked",
  "lang.aria": "Language",
  "cook.haveTitle": "What's in the fridge",
  "cook.haveHint": "Type a name and press Enter. Commas work for several at once.",
  "cook.clearAll": "Clear all",
  "cook.ingredientPlaceholder": "e.g. eggs",
  "cook.ingredientAria": "Add ingredient",
  "cook.dishTitle": "Dish you want (optional)",
  "cook.dishHint": "Leave empty to get ideas. Fill it in to get that recipe.",
  "cook.dishPlaceholder": "e.g. kimchi fried rice",
  "cook.dishAria": "Dish you want",
  "cook.avoidTitle": "Leave these out",
  "cook.avoidHint": "Allergies or things you don't want to eat.",
  "cook.avoidPlaceholder": "e.g. shrimp",
  "cook.avoidAria": "Add ingredient to avoid",
  "cook.servings": "Servings",
  "cook.minutes": "Time",
  "cook.min15": "15 min",
  "cook.min30": "30 min",
  "cook.min60": "1 hour",
  "cook.minAny": "No rush",
  "cook.taste": "Flavor",
  "cook.tasteMild": "Mild",
  "cook.tasteSpicy": "Spicy",
  "cook.tasteAny": "Anything",
  "cook.cuisine": "Style",
  "cook.cuisineKorean": "Korean",
  "cook.cuisineWestern": "Western",
  "cook.cuisineJapanese": "Japanese",
  "cook.cuisineChinese": "Chinese",
  "cook.cuisineSeasia": "SE Asian",
  "cook.cuisineAny": "Anything",
  "video.title": "Watch someone make it",
  "video.hint": "Opens a real search for your ingredients and style — safer than links an AI invents.",
  "video.empty": "Add ingredients or a dish name to get search buttons.",
  "video.youtube": "YouTube",
  "video.shorts": "YouTube Shorts",
  "video.instagram": "Instagram",
  "video.keyword": "Search: {q}",
  "cook.promptTitle": "AI prompt",
  "cook.promptHint": "Copy and paste into ChatGPT, Claude, or Gemini.",
  "cook.copy": "Copy",
  "cook.copied": "Copied",
  "cook.copyRetry": "Try again",
  "cook.promptEmpty": "Add ingredients or a dish name to build a prompt.",
  "shop.title": "Need to buy",
  "shop.hint": "Anything already in the fridge is skipped. Check an item after you buy it to move it to the fridge.",
  "shop.placeholder": "e.g. sesame oil",
  "shop.aria": "Add shopping item",
  "shop.empty": "Nothing to buy yet. Paste the missing ingredients from the AI reply.",
  "shop.copy": "Copy list",
  "shop.copied": "Copied",
  "shop.count": "{n} to buy",
  "shop.boughtAria": "Bought {name}",
  "shop.clear": "Clear list",
  "journal.recent": "Recently cooked",
  "journal.empty": "Nothing saved yet. Add a dish and paste the recipe.",
  "journal.titlePlaceholder": "Dish you cooked",
  "journal.recipePlaceholder": "Paste the recipe",
  "journal.notePlaceholder": "Note (optional) e.g. less salt next time",
  "journal.titleAria": "Dish name",
  "journal.recipeAria": "Recipe",
  "journal.noteAria": "Note",
  "journal.save": "Save for this day",
  "journal.saveEdit": "Save edits",
  "journal.cancel": "Cancel edit",
  "journal.edit": "Edit",
  "journal.delete": "Delete",
  "journal.prevMonth": "Previous month",
  "journal.nextMonth": "Next month",
  "chips.more": "Add more",
  "chips.remove": "Remove",
  "footer.privacy": "Saved only in this browser. Nothing is sent to a server.",
};
