export const en = {
  "meta.title": "What's for dinner?",
  "meta.description":
    "Turn fridge ingredients into an AI cooking prompt, and keep a shopping list of only what you don't have.",
  "app.title": "What's for dinner?",
  "app.lede": "Add ingredients, copy a prompt, paste it into ChatGPT or Claude.",
  "deck.aria": "Pick a tool",
  "deck.cook": "Cooking prompt",
  "deck.analyze": "Video analysis",
  "analyze.metaTitle": "Rewrite",
  "analyze.title": "Rewrite",
  "analyze.lede": "Paste a video link and get an analysis prompt to hand to an AI.",
  "analyze.linkTitle": "Video link",
  "analyze.linkHint": "YouTube transcripts come along automatically. Instagram and TikTok work with just a link.",
  "analyze.linkPlaceholder": "https://www.youtube.com/shorts/",
  "analyze.linkAria": "Video link",
  "analyze.pasteToggle": "Paste a script instead",
  "analyze.scriptPlaceholder": "If you have the script, paste it here (optional)",
  "analyze.scriptAria": "Script",
  "analyze.submit": "Make prompt",
  "analyze.demo": "See a sample first",
  "analyze.itemsTitle": "What it analyzes",
  "analyze.itemsHint": "The prompt asks for these five things, in order.",
  "analyze.promptTitle": "Analysis prompt",
  "analyze.promptHint": "Copy and paste into ChatGPT, Claude, or Gemini.",
  "analyze.promptEmpty": "Paste a video link and the prompt lands here.",
  "analyze.copy": "Copy",
  "analyze.copied": "Copied",
  "analyze.copyRetry": "Try again",
  "analyze.progressCheck": "Checking the link",
  "analyze.progressScript": "Fetching the transcript",
  "analyze.progressHook": "Listing what to analyze",
  "analyze.progressReuse": "Building the prompt",
  "analyze.errEmpty": "Paste a video link first.",
  "analyze.errUnsupported": "Use a YouTube, Shorts, Instagram, TikTok, or Facebook link.",
  "tabs.aria": "Pages",
  "tabs.cook": "Cook",
  "tabs.shop": "Shop",
  "tabs.journal": "Cooked",
  "lang.aria": "Language",
  "cook.haveTitle": "What's in the fridge",
  "cook.haveHint": "Type a name and press Enter. Commas work for several at once.",
  "cook.clearAll": "Clear all",
  "cook.ingredientPlaceholder": "e.g. eggs",
  "cook.ingredientAria": "Add ingredient",
  "cook.quickTitle": "Quick picks",
  "cook.quickEdit": "Edit",
  "cook.quickDone": "Done",
  "cook.quickReset": "Reset",
  "cook.quickAddPlaceholder": "Add an ingredient to quick picks",
  "cook.quickAddAria": "Add an ingredient to quick picks",
  "cook.quickRemove": "Remove {name} from quick picks",
  "cook.dishTitle": "Dish you want (optional)",
  "cook.dishHint": "Leave empty to get ideas. Fill it in to get that recipe.",
  "cook.dishPlaceholder": "e.g. kimchi fried rice",
  "cook.dishAria": "Dish you want",
  "cook.avoidTitle": "Leave these out",
  "cook.avoidHint": "Allergies or things you don't want to eat.",
  "cook.avoidPlaceholder": "e.g. shrimp",
  "cook.avoidAria": "Add ingredient to avoid",
  "cook.servings": "Servings",
  "cook.minutes": "Time",
  "cook.min15": "15 min",
  "cook.min30": "30 min",
  "cook.min60": "1 hour",
  "cook.minAny": "No rush",
  "cook.taste": "Flavor",
  "cook.tasteMild": "Mild",
  "cook.tasteSpicy": "Spicy",
  "cook.tasteAny": "Anything",
  "cook.cuisine": "Style",
  "cook.cuisineKorean": "Korean",
  "cook.cuisineWestern": "Western",
  "cook.cuisineJapanese": "Japanese",
  "cook.cuisineChinese": "Chinese",
  "cook.cuisineSeasia": "SE Asian",
  "cook.cuisineAny": "Anything",
  "video.title": "Watch someone make it",
  "video.hint": "Opens a real search for your ingredients and style — safer than links an AI invents.",
  "video.empty": "Add ingredients or a dish name to get search buttons.",
  "video.youtube": "YouTube",
  "video.shorts": "YouTube Shorts",
  "video.instagram": "Instagram",
  "video.keyword": "Search: {q}",
  "cook.promptTitle": "AI prompt",
  "cook.promptHint": "Copy and paste into ChatGPT, Claude, or Gemini.",
  "cook.copy": "Copy",
  "cook.copied": "Copied",
  "cook.copyRetry": "Try again",
  "cook.promptEmpty": "Add ingredients or a dish name to build a prompt.",
  "shop.title": "Need to buy",
  "shop.hint": "Anything already in the fridge is skipped. Check an item after you buy it to move it to the fridge.",
  "shop.placeholder": "e.g. sesame oil",
  "shop.aria": "Add shopping item",
  "shop.empty": "Nothing to buy yet. Paste the missing ingredients from the AI reply.",
  "shop.copy": "Copy list",
  "shop.copied": "Copied",
  "shop.count": "{n} to buy",
  "shop.boughtAria": "Bought {name}",
  "shop.clear": "Clear list",
  "journal.recent": "Recently cooked",
  "journal.empty": "Nothing saved yet. Add a dish and paste the recipe.",
  "journal.titlePlaceholder": "Dish you cooked",
  "journal.recipePlaceholder": "Paste the recipe",
  "journal.notePlaceholder": "Note (optional) e.g. less salt next time",
  "journal.titleAria": "Dish name",
  "journal.recipeAria": "Recipe",
  "journal.noteAria": "Note",
  "journal.addPhoto": "Add photo",
  "journal.removePhoto": "Remove photo",
  "journal.photoAlt": "Photo of {title}",
  "journal.save": "Save for this day",
  "journal.saveEdit": "Save edits",
  "journal.cancel": "Cancel edit",
  "journal.edit": "Edit",
  "journal.delete": "Delete",
  "journal.prevMonth": "Previous month",
  "journal.nextMonth": "Next month",
  "chips.more": "Add more",
  "chips.remove": "Remove",
  "storage.full": "Storage is full. Delete older entries or photos, then save again.",
  "footer.privacy": "Saved only in this browser. Nothing is sent to a server.",
  "analyze.privacy": "Only YouTube transcripts are fetched on this computer. Videos are not stored.",
};
