export const ko = {
  "meta.title": "오늘 뭐 해먹지",
  "meta.description":
    "냉장고 재료로 AI 요리 프롬프트를 만들고, 없는 재료는 장보기로 모아 두세요.",
  "app.title": "오늘 뭐 해먹지",
  "app.lede": "재료를 넣으면 AI에 바로 붙여넣을 프롬프트가 생겨요.",
  "tabs.aria": "페이지",
  "tabs.cook": "요리 찾기",
  "tabs.shop": "장보기",
  "tabs.journal": "해먹은 요리",
  "lang.aria": "언어",
  "cook.haveTitle": "지금 있는 재료",
  "cook.haveHint": "이름 쓰고 엔터. 쉼표로 여러 개도 넣을 수 있어요.",
  "cook.clearAll": "모두 지우기",
  "cook.ingredientPlaceholder": "예: 달걀",
  "cook.ingredientAria": "재료 추가",
  "cook.dishTitle": "만들고 싶은 요리 (선택)",
  "cook.dishHint": "비워 두면 재료로 요리를 찾고, 채우면 그 요리 레시피를 찾아요.",
  "cook.dishPlaceholder": "예: 김치볶음밥",
  "cook.dishAria": "만들고 싶은 요리",
  "cook.avoidTitle": "빼고 싶은 재료",
  "cook.avoidHint": "알러지거나 먹기 싫은 건 여기에 넣어요.",
  "cook.avoidPlaceholder": "예: 새우",
  "cook.avoidAria": "빼고 싶은 재료 추가",
  "cook.servings": "몇 인분",
  "cook.minutes": "시간은",
  "cook.min15": "15분",
  "cook.min30": "30분",
  "cook.min60": "1시간",
  "cook.minAny": "여유 있게",
  "cook.taste": "맛",
  "cook.tasteMild": "담백",
  "cook.tasteSpicy": "매콤",
  "cook.tasteAny": "아무거나",
  "cook.cuisine": "분위기",
  "cook.cuisineKorean": "한식",
  "cook.cuisineWestern": "양식",
  "cook.cuisineJapanese": "일식",
  "cook.cuisineChinese": "중식",
  "cook.cuisineSeasia": "동남아",
  "cook.cuisineAny": "아무거나",
  "video.title": "영상으로 보기",
  "video.hint": "지금 재료와 분위기로 검색 결과를 열어요. AI가 준 링크보다 확실해요.",
  "video.empty": "재료를 넣거나 요리 이름을 쓰면 검색 버튼이 생겨요.",
  "video.youtube": "유튜브",
  "video.shorts": "유튜브 쇼츠",
  "video.instagram": "인스타그램",
  "video.keyword": "검색어: {q}",
  "cook.promptTitle": "AI 프롬프트",
  "cook.promptHint": "복사해서 ChatGPT, Claude, Gemini에 붙여넣으세요.",
  "cook.copy": "복사하기",
  "cook.copied": "복사됨",
  "cook.copyRetry": "다시 시도",
  "cook.promptEmpty": "재료를 넣거나 요리 이름을 쓰면 여기에 프롬프트가 생겨요.",
  "shop.title": "사야 하는 재료",
  "shop.hint": "집에 이미 있는 재료는 자동으로 빠져요. 산 건 체크하면 냉장고로 옮겨요.",
  "shop.placeholder": "예: 참기름",
  "shop.aria": "장보기 재료 추가",
  "shop.empty": "아직 살 게 없어요. AI가 적어 준 없는 재료를 붙여넣으세요.",
  "shop.copy": "목록 복사",
  "shop.copied": "복사됨",
  "shop.count": "{n}가지를 사야 해요",
  "shop.boughtAria": "{name} 샀어요",
  "shop.clear": "목록 비우기",
  "journal.recent": "최근 해먹은 요리",
  "journal.empty": "아직 기록이 없어요. 해먹은 요리와 레시피를 남겨 보세요.",
  "journal.titlePlaceholder": "해먹은 요리 이름",
  "journal.recipePlaceholder": "레시피를 붙여넣으세요",
  "journal.notePlaceholder": "메모 (선택) 예: 다음엔 덜 짜게",
  "journal.titleAria": "요리 이름",
  "journal.recipeAria": "레시피",
  "journal.noteAria": "메모",
  "journal.save": "이 날 기록 저장",
  "journal.saveEdit": "수정 저장",
  "journal.cancel": "수정 취소",
  "journal.edit": "수정",
  "journal.delete": "삭제",
  "journal.prevMonth": "이전 달",
  "journal.nextMonth": "다음 달",
  "chips.more": "더 넣기",
  "chips.remove": "지우기",
  "footer.privacy": "재료와 기록은 이 브라우저에만 저장돼요. 서버로 보내지 않아요.",
};
