export const ko = {
  "meta.title": "오늘 뭐 해먹지",
  "meta.description":
    "냉장고 재료로 AI 요리 프롬프트를 만들고, 없는 재료는 장보기로 모아 두세요.",
  "app.title": "오늘 뭐 해먹지",
  "app.lede": "재료를 넣으면 AI에 바로 붙여넣을 프롬프트가 생겨요.",
  "deck.aria": "도구 고르기",
  "deck.cook": "요리 프롬프트",
  "deck.analyze": "영상 분석",
  "analyze.metaTitle": "다시쓰기",
  "analyze.title": "다시쓰기",
  "analyze.lede": "영상 링크를 넣으면 AI에 붙여넣을 분석 프롬프트가 생겨요.",
  "analyze.linkTitle": "영상 링크",
  "analyze.linkHint": "유튜브는 대본까지 같이 가져와요. 인스타·틱톡은 링크만 넣어도 돼요.",
  "analyze.linkPlaceholder": "https://www.youtube.com/shorts/",
  "analyze.linkAria": "영상 링크",
  "analyze.pasteToggle": "대본 직접 붙여넣기",
  "analyze.scriptPlaceholder": "대본이 있으면 여기에 붙여넣으세요 (선택)",
  "analyze.scriptAria": "대본",
  "analyze.submit": "프롬프트 만들기",
  "analyze.demo": "예시로 먼저 보기",
  "analyze.itemsTitle": "이런 걸 분석해요",
  "analyze.itemsHint": "프롬프트에 아래 다섯 가지가 순서대로 들어가요.",
  "analyze.promptTitle": "분석 프롬프트",
  "analyze.promptHint": "복사해서 ChatGPT, Claude, Gemini에 붙여넣으세요.",
  "analyze.promptEmpty": "영상 링크를 넣으면 여기에 프롬프트가 생겨요.",
  "analyze.copy": "복사하기",
  "analyze.copied": "복사됨",
  "analyze.copyRetry": "다시 시도",
  "analyze.progressCheck": "링크 확인 중",
  "analyze.progressScript": "대본 가져오는 중",
  "analyze.progressHook": "분석 항목 정리 중",
  "analyze.progressReuse": "프롬프트 만드는 중",
  "analyze.errEmpty": "영상 링크를 붙여넣어 주세요.",
  "analyze.errUnsupported": "유튜브, 쇼츠, 인스타, 틱톡, 페이스북 링크를 넣어 주세요.",
  "tabs.aria": "페이지",
  "tabs.cook": "요리 찾기",
  "tabs.shop": "장보기",
  "tabs.journal": "해먹은 요리",
  "lang.aria": "언어",
  "cook.haveTitle": "지금 있는 재료",
  "cook.haveHint": "이름 쓰고 엔터. 쉼표로 여러 개도 넣을 수 있어요.",
  "cook.clearAll": "모두 지우기",
  "cook.ingredientPlaceholder": "예: 달걀",
  "cook.ingredientAria": "재료 추가",
  "cook.quickTitle": "빠른 선택",
  "cook.quickEdit": "편집",
  "cook.quickDone": "편집 끝",
  "cook.quickReset": "기본으로",
  "cook.quickAddPlaceholder": "빠른 선택에 추가할 재료",
  "cook.quickAddAria": "빠른 선택에 재료 추가",
  "cook.quickRemove": "빠른 선택에서 {name} 빼기",
  "cook.dishTitle": "만들고 싶은 요리 (선택)",
  "cook.dishHint": "비워 두면 재료로 요리를 찾고, 채우면 그 요리 레시피를 찾아요.",
  "cook.dishPlaceholder": "예: 김치볶음밥",
  "cook.dishAria": "만들고 싶은 요리",
  "cook.avoidTitle": "빼고 싶은 재료",
  "cook.avoidHint": "알러지거나 먹기 싫은 건 여기에 넣어요.",
  "cook.avoidPlaceholder": "예: 새우",
  "cook.avoidAria": "빼고 싶은 재료 추가",
  "cook.servings": "몇 인분",
  "cook.minutes": "시간은",
  "cook.min15": "15분",
  "cook.min30": "30분",
  "cook.min60": "1시간",
  "cook.minAny": "여유 있게",
  "cook.taste": "맛",
  "cook.tasteMild": "담백",
  "cook.tasteSpicy": "매콤",
  "cook.tasteAny": "아무거나",
  "cook.cuisine": "분위기",
  "cook.cuisineKorean": "한식",
  "cook.cuisineWestern": "양식",
  "cook.cuisineJapanese": "일식",
  "cook.cuisineChinese": "중식",
  "cook.cuisineSeasia": "동남아",
  "cook.cuisineAny": "아무거나",
  "video.title": "영상으로 보기",
  "video.hint": "지금 재료와 분위기로 검색 결과를 열어요. AI가 준 링크보다 확실해요.",
  "video.empty": "재료를 넣거나 요리 이름을 쓰면 검색 버튼이 생겨요.",
  "video.youtube": "유튜브",
  "video.shorts": "유튜브 쇼츠",
  "video.instagram": "인스타그램",
  "video.keyword": "검색어: {q}",
  "cook.promptTitle": "AI 프롬프트",
  "cook.promptHint": "복사해서 ChatGPT, Claude, Gemini에 붙여넣으세요.",
  "cook.copy": "복사하기",
  "cook.copied": "복사됨",
  "cook.copyRetry": "다시 시도",
  "cook.promptEmpty": "재료를 넣거나 요리 이름을 쓰면 여기에 프롬프트가 생겨요.",
  "shop.title": "사야 하는 재료",
  "shop.hint": "집에 이미 있는 재료는 자동으로 빠져요. 산 건 체크하면 냉장고로 옮겨요.",
  "shop.placeholder": "예: 참기름",
  "shop.aria": "장보기 재료 추가",
  "shop.empty": "아직 살 게 없어요. AI가 적어 준 없는 재료를 붙여넣으세요.",
  "shop.copy": "목록 복사",
  "shop.copied": "복사됨",
  "shop.count": "{n}가지를 사야 해요",
  "shop.boughtAria": "{name} 샀어요",
  "shop.clear": "목록 비우기",
  "journal.recent": "최근 해먹은 요리",
  "journal.empty": "아직 기록이 없어요. 해먹은 요리와 레시피를 남겨 보세요.",
  "journal.titlePlaceholder": "해먹은 요리 이름",
  "journal.recipePlaceholder": "레시피를 붙여넣으세요",
  "journal.notePlaceholder": "메모 (선택) 예: 다음엔 덜 짜게",
  "journal.titleAria": "요리 이름",
  "journal.recipeAria": "레시피",
  "journal.noteAria": "메모",
  "journal.addPhoto": "사진 넣기",
  "journal.removePhoto": "사진 지우기",
  "journal.photoAlt": "{title} 사진",
  "journal.save": "이 날 기록 저장",
  "journal.saveEdit": "수정 저장",
  "journal.cancel": "수정 취소",
  "journal.edit": "수정",
  "journal.delete": "삭제",
  "journal.prevMonth": "이전 달",
  "journal.nextMonth": "다음 달",
  "chips.more": "더 넣기",
  "chips.remove": "지우기",
  "storage.full": "저장 공간이 가득 찼어요. 오래된 기록이나 사진을 지우고 다시 저장해 주세요.",
  "footer.privacy": "재료와 기록은 이 브라우저에만 저장돼요. 서버로 보내지 않아요.",
  "analyze.privacy": "유튜브 대본만 이 컴퓨터에서 가져와요. 영상 파일은 저장하지 않아요.",
};
